# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: format
        name: Format code
        entry: make fmt
        language: system
        types: [go]

      - id: lint
        name: Lint
        entry: make lint
        language: system
        pass_filenames: false

      - id: unittests
        name: Unit tests
        entry: make test
        language: system
        pass_filenames: false
