version: "3.7"
services:
  app:
    build:
      context: .
      target: dev
    env_file: .env
    volumes:
      - .:/src/app
    ports:
      - "${APP_PORT:-5000}"

  db:
    image: library/postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DB_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "${NGINX_PROXY_PORT:-80}:80"
      - "${NGINX_PROXY_PORT_HTTPS:-443}:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      com.github.aegypius.mkcert-for-nginx-proxy.nginx_proxy: ''

  mkcert:
    image: aegypius/mkcert-for-nginx-proxy
    restart: unless-stopped
    volumes:
      - ssl-certs:/app/certs:rw
      - ~/.mozilla/firefox:/root/.mozilla/firefox:rw
      - ~/.pki/nssdb:/root/.pki/nssdb:rw
      - ${CA_STORE:-/usr/local/share/ca-certificates}:/usr/local/share/ca-certificates
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  ssl-certs: {}
  db-data:
    driver: local
