// Code generated by mockery v2.3.0. DO NOT EDIT.

package todo

import mock "github.com/stretchr/testify/mock"

// MockCreateUseCase is an autogenerated mock type for the CreateUseCase type
type MockCreateUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: request
func (_m *MockCreateUseCase) Execute(request CreateTodo) (Todo, error) {
	ret := _m.Called(request)

	var r0 Todo
	if rf, ok := ret.Get(0).(func(CreateTodo) Todo); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Get(0).(Todo)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(CreateTodo) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
