name: Build Docs
on:
  push:
    branches:
      - master
      - development
    paths:
      - 'docs/**'
  workflow_dispatch:

env:
  NODE_VERSION: '12.x'

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1.4.4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build Content Docs
        run: cd docs && yarn install && yarn generate

      - name: Build API Docs
        run: cd docs && yarn redoc:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/dist
