name: CI
env:
  TEST: true
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Check out code
        uses: actions/checkout@v1

      - name: Lint Go Code
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -u github.com/mgechev/revive
          make lint

  lint-dockerfile:
    runs-on: ubuntu-latest
    container: pipelinecomponents/hadolint:latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint Dockerfile
        run: hadolint Dockerfile

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Unit tests.
        run: make test-coverage

      - name: Upload coverage report to Codacy
        run: |
            export PATH=$PATH:$(go env GOPATH)/bin
            go get github.com/schrej/godacov
            godacov -t $CODACY_TOKEN -r ./test/cover/cover.out -c $GITHUB_SHA
        env:
          CODACY_TOKEN: ${{secrets.CODACY_TOKEN}}

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .
        env:
          IMAGE_NAME: go-api-sample:${{github.sha}}

      - name: Save image
        run:  docker save -o image.tar $IMAGE_NAME
        env:
          IMAGE_NAME: go-api-sample:${{github.sha}}

      - name: Upload image artifact
        uses: actions/upload-artifact@master
        with:
          name: image
          path: image.tar

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [build-docker]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Check out code
        uses: actions/checkout@v1

      - name: Pull Image artifact
        uses: actions/download-artifact@master
        with:
          name: image

      - name: Load image into docker
        run: docker load -i image/image.tar

      - name: Run application
        run: docker run -d -e APP_ENV=prod -e APP_PORT=5000 -p 5000:5000 go-api-sample:$GITHUB_SHA

      - name: Run Godog integration tests
        run: make test-functional
        env:
          APP_BASE_URL: http://localhost:5000

  push-to-gcr:
    name: Push Docker image to Google Cloud Registry
    runs-on: ubuntu-latest
    needs: ['integration-tests']
    steps:
      - name: Pull Image artifact
        uses: actions/download-artifact@master
        with:
          name: image
      - name: Load image into docker
        run: docker load -i image/image.tar

      - name: Login in GCR
        run:  docker login -u _json_key -p "$GCLOUD_SERVICE_KEY" https://gcr.io
        env:
          GCLOUD_SERVICE_KEY: ${{secrets.GCLOUD_SERVICE_KEY}}

      - name: Tag and push images to Registry
        run: |
          echo $IMAGE_NAME
          docker tag go-api-sample:$GITHUB_SHA gcr.io/$GCLOUD_PROJECT_ID/go-api-sample:$(echo $GITHUB_SHA | cut -c1-8)
          docker tag go-api-sample:$GITHUB_SHA gcr.io/$GCLOUD_PROJECT_ID/go-api-sample:latest
          docker push gcr.io/$GCLOUD_PROJECT_ID/go-api-sample:latest
        env:
          GCLOUD_PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          IMAGE_NAME: go-api-sample:${{github.sha}}

  deploy:
    runs-on: ubuntu-latest
    needs: ['push-to-gcr']
    container: google/cloud-sdk:alpine
    steps:
      - name: Authenticate on Google Cloud
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
          gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
        env:
          GCLOUD_SERVICE_KEY: ${{secrets.GCLOUD_SERVICE_KEY}}
      - name: Deploy to Cloud Run
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          gcloud components update --quiet
          gcloud beta run deploy --image gcr.io/$GCLOUD_PROJECT_ID/go-api-sample \
            --platform managed \
            --set-env-vars APP_ENV=prod
        env:
          GCLOUD_PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
      - name: After Deploy
        run: rm -f ${HOME}/gcloud-service-key.json
