name: CI
on:
  push:
    branches:
      - master
  pull_request:

env:
  IMAGE_NAME: go-api-sample:${{ github.sha }}
  GO_VERSION: 1.14
  GO111MODULE: on

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.30

  lint-dockerfile:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@master

  gosec:
    name: Gosec Security Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v2

      - uses: securego/gosec@master
        with:
          args: -fmt=JUnit XML -out gosec-results.xml  ./...
        env:
          - GOROOT: ""

      - uses: ashley-taylor/junit-report-annotations-action@1.3
        if: always()
        with:
          name: Gosec Security Results
          path: gosec.xml
          access-token: ${{ secrets.GITHUB_TOKEN }}

  unittests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [lint, lint-dockerfile]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v0.1.0
        with:
            gotestsum_version: 0.4.1

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Unit tests
        run: gotestsum --junitfile test-report.xml -- -coverprofile=cover.out

      - uses: ashley-taylor/junit-report-annotations-action@1.3
        if: always()
        with:
          name: Test Results
          path: test-report.xml
          access-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage report to Codacy
        uses: brpaz/godacov-action@master
        if: always()
        with:
          reportPath: 'cover.out'
          codacyToken: ${{ secrets.CODACY_TOKEN }}
          commitId: ${{ github.sha }}

  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [lint, lint-dockerfile, unittests, gosec]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Image
        run: |
          echo $IMAGE_NAME
          docker build \
           --target production \
            --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg VCS_REF=`git rev-parse --short HEAD` \
            --build-arg VERSION=`1.0.0` \
           -t $IMAGE_NAME .

      - name: Run Container Tests
        uses: brpaz/structure-tests-action@v1
        with:
          image: $IMAGE_NAME
          configFile: container-structure-test.yaml

  acceptance-tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo "Integration tests"

  deploy:
    name: Deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo "deploy"
