name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
env:
  TEST_IMAGE_NAME: go-api-sample:${{ github.sha }}
  GO_VERSION: 1.15
  GO111MODULE: on

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      TEST_IMAGE_NAME: go-api-sample-${{ steps.short-sha.outputs.sha }}
    steps:
      - uses: benjlevesque/short-sha@v1.1
        id: short-sha

  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - run:  echo ${{ needs.prepare.outputs.TEST_IMAGE_NAME }}
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.31

  lint-dockerfile:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@master

  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [lint, lint-dockerfile]
    steps:
      - run:  echo ${{ needs.prepare.outputs.TEST_IMAGE_NAME }}
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v0.1.0
        with:
            gotestsum_version: 0.4.1

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: gotestsum --junitfile test-report.xml -- -v -tags=unit -cover -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload test results artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit Tests Report
          path: test-report.xml

      - uses: ashley-taylor/junit-report-annotations-action@master
        if: always()
        with:
          name: Unit Tests Report
          path: test-report.xml
          access-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
        if: success()
        with:
          file: ./coverage.txt

  test-integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [test-unit]
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: chu0eiXa
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v0.1.0
        with:
          gotestsum_version: 0.4.1

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: go run test/integration/db/main.go
        env:
          APP_ENV: test
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: app
          DB_DATABASE: app
          DB_PASSWORD: chu0eiXa

  build-image:
    name: Build And Test Image
    runs-on: ubuntu-latest
    needs: [test-unit, test-integration]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Image
        run: |
          docker build \
           --target production \
            --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg VCS_REF=`git rev-parse --short HEAD` \
            --build-arg VERSION=`1.0.0` \
           -t $TEST_IMAGE_NAME .

      - name: Run Container Structure Tests
        uses: brpaz/structure-tests-action@v1.1.2
        with:
          image: ${{ env.TEST_IMAGE_NAME }}
          configFile: container-structure-test.yaml

      - name: Vulerability Scan
        uses: anchore/scan-action@v2
        with:
          image: ${{ env.TEST_IMAGE_NAME }}
          fail-build: true
          severity-cutoff: critical

      - name: Save image
        run:  mkdir -p /tmp/docker-image-cache && docker save -o /tmp/docker-image-cache/image.tar $TEST_IMAGE_NAME

      - name: Setup Docker Image Cache
        uses: actions/cache@v2
        with:
            path: /tmp/docker-image-cache
            key: docker-cache-${{ github.sha }}

  acceptance-tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    needs: [build-image]
    env:
      APP_ENV: test
      APP_PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: app
      DB_DATABASE: app_test
      DB_PASSWORD: chu0eiXa
      APP_URL: http://127.0.0.1:3000
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD:  ${{ env.DB_PASSWORD }}
          POSTGRES_DB:  ${{ env.DB_DATABASE }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v0.1.0
        with:
            gotestsum_version: 0.4.1

      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Docker Image Cache
        uses: actions/cache@v2
        with:
          path: /tmp/docker-image-cache
          key: docker-cache-${{ github.sha }}

      - name: Load Image
        run:  docker load -i /tmp/docker-image-cache/image.tar

      - uses: CallePuzzle/envvar-to-dotenv-action@0.1.0
        with:
          variableNames: APP_ENV,APP_PORT,DB_HOST,DB_PORT,DB_USER,DB_PASSWORD,DB_DATABASE
          envPath: .env.test

      - name: Run application
        run: |
          docker run --name="app" -d --network "${{ job.services.postgres.network }}" -p 3000:3000 --env-file=.env.test $TEST_IMAGE_NAME

      - name: Wait for application to start
        run: curl -sS --retry-connrefused --connect-timeout 5 --retry 5 --retry-delay 0 --retry-max-time 30 ${APP_URL}

      - name: Run Database migrations
        run: docker exec -t app migrate -path=migrations -database postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?sslmode=disable up

      - name: Run tests
        run: go test -v ./test/acceptance -tags=acceptance -count=1
        env:
          SETUP_DB: false
          DB_HOST: localhost

#  push-to-gcr:
#    name: Push Docker image to Google Cloud Registry
#    runs-on: ubuntu-latest
#    needs: ['acceptance-tests']
#    steps:
#
#      - name: Setup Docker Image Cache
#          uses: actions/cache@v2
#          with:
#            path: /tmp/docker-image-cache
#            key: docker-cache-${{ github.sha }}
#
#      - name: Load image into docker
#        run: docker load -i image/image.tar
#
#      - name: Login in GCR
#        run:  docker login -u _json_key -p "$GCLOUD_SERVICE_KEY" https://gcr.io
#        env:
#          GCLOUD_SERVICE_KEY: ${{secrets.GCLOUD_SERVICE_KEY}}
#
#      - name: Tag and push images to Registry
#        run: |
#          docker tag $TEST_IMAGE_NAME $RELEASE_IMAGE_NAME:$GITHUB_SHA
#          docker tag $TEST_IMAGE_NAME $RELEASE_IMAGE_NAME:latest
#          docker push $RELEASE_IMAGE_NAME:$GITHUB_SHA
#          docker push $RELEASE_IMAGE_NAME:latest


#  deploy:
#    name: Deploy
#    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
#    runs-on: ubuntu-latest
#    needs: [acceptance-tests]
#    steps:
#      - run: echo "deploy"
