name: Release
on:
  workflow_dispatch:

env:
  RELEASE_IMAGE: 'brpaz/go-api-sample'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull image
        run: docker pull ${{ env.RELEASE_IMAGE }}:${{ env.SHORT_SHA }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/github@7.1.1
            @eclass/semantic-release-docker@1.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
